import { useState } from 'react';
import { Building2,Edit3,Plus,Trash2 } from 'lucide-react';
import { PageHeader,Panel,FormField,FormGrid } from '../../../core/ui';
import Modal from '../../../core/ui/Modal';
import { useAdmin } from '../AdmContext';
export default function Organization(){const {state,actions}=useAdmin();const [branch,setBranch]=useState(null);const [dept,setDept]=useState(null);const branchName=(id)=>state.branches.find((b)=>b.branchId===id)?.name||'—';
 const delBranch=(r)=>{if(window.confirm(`Delete ${r.name}?`))try{actions.deleteBranch(r.branchId)}catch(e){window.alert(e.message)}};const delDept=(r)=>{if(window.confirm(`Delete ${r.name}?`))try{actions.deleteDepartment(r.deptId)}catch(e){window.alert(e.message)}};
 return <div><PageHeader title="Organisation Directory" subtitle="Maintain branches, Head Office units, and branch-level departments."/><div className="adm-grid"><Panel title={`Branches (${state.branches.length})`} action={<button className="btn btn-primary" onClick={()=>setBranch({})}><Plus size={14}/>Add branch</button>} padded={false}><div className="adm-table-wrap"><table className="ui-table"><thead><tr><th>Code</th><th>Name</th><th>Type</th><th>Status</th><th>Actions</th></tr></thead><tbody>{state.branches.map((r)=><tr key={r.branchId}><td className="code">{r.code}</td><td><strong>{r.name}</strong></td><td>{r.type}</td><td><span className={`adm-status ${r.status.toLowerCase()}`}>{r.status}</span></td><td><div className="adm-actions"><button onClick={()=>setBranch(r)}><Edit3 size={14}/></button><button className="danger" onClick={()=>delBranch(r)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div></Panel>
 <Panel title={`Departments (${state.departments.length})`} action={<button className="btn btn-primary" onClick={()=>setDept({})}><Plus size={14}/>Add department</button>} padded={false}><div className="adm-table-wrap"><table className="ui-table"><thead><tr><th>Code</th><th>Name</th><th>Branch</th><th>Status</th><th>Actions</th></tr></thead><tbody>{state.departments.map((r)=><tr key={r.deptId}><td className="code">{r.code}</td><td><strong>{r.name}</strong></td><td>{branchName(r.branchId)}</td><td><span className={`adm-status ${r.status.toLowerCase()}`}>{r.status}</span></td><td><div className="adm-actions"><button onClick={()=>setDept(r)}><Edit3 size={14}/></button><button className="danger" onClick={()=>delDept(r)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div></Panel></div>
 {branch&&<BranchModal row={branch} onClose={()=>setBranch(null)} onSave={(p)=>{try{branch.branchId?actions.updateBranch(branch.branchId,p):actions.addBranch(p);setBranch(null)}catch(e){window.alert(e.message)}}}/>} {dept&&<DeptModal row={dept} branches={state.branches} onClose={()=>setDept(null)} onSave={(p)=>{try{dept.deptId?actions.updateDepartment(dept.deptId,p):actions.addDepartment(p);setDept(null)}catch(e){window.alert(e.message)}}}/>}</div>}
function BranchModal({row,onClose,onSave}){const [f,setF]=useState({code:row.code||'',name:row.name||'',type:row.type||'BRANCH',status:row.status||'ACTIVE'});const s=(k,v)=>setF((o)=>({...o,[k]:v}));return <Modal title={`${row.branchId?'Edit':'Add'} Branch`} onClose={onClose} footer={<><button className="btn btn-secondary" onClick={onClose}>Cancel</button><button className="btn btn-primary" onClick={()=>onSave(f)}>Save</button></>}><FormGrid><FormField label="Code" required><input value={f.code} onChange={(e)=>s('code',e.target.value)}/></FormField><FormField label="Name" required><input value={f.name} onChange={(e)=>s('name',e.target.value)}/></FormField><FormField label="Type"><select value={f.type} onChange={(e)=>s('type',e.target.value)}><option>HEAD_OFFICE</option><option>BRANCH</option><option>HUB</option></select></FormField><FormField label="Status"><select value={f.status} onChange={(e)=>s('status',e.target.value)}><option>ACTIVE</option><option>INACTIVE</option></select></FormField></FormGrid></Modal>}
function DeptModal({row,branches,onClose,onSave}){const [f,setF]=useState({code:row.code||'',name:row.name||'',branchId:row.branchId||branches[0]?.branchId,status:row.status||'ACTIVE'});const s=(k,v)=>setF((o)=>({...o,[k]:v}));return <Modal title={`${row.deptId?'Edit':'Add'} Department`} onClose={onClose} footer={<><button className="btn btn-secondary" onClick={onClose}>Cancel</button><button className="btn btn-primary" onClick={()=>onSave(f)}>Save</button></>}><FormGrid><FormField label="Code" required><input value={f.code} onChange={(e)=>s('code',e.target.value)}/></FormField><FormField label="Name" required><input value={f.name} onChange={(e)=>s('name',e.target.value)}/></FormField><FormField label="Branch / Office" required><select value={f.branchId} onChange={(e)=>s('branchId',e.target.value)}>{branches.map((b)=><option key={b.branchId} value={b.branchId}>{b.name}</option>)}</select></FormField><FormField label="Status"><select value={f.status} onChange={(e)=>s('status',e.target.value)}><option>ACTIVE</option><option>INACTIVE</option></select></FormField></FormGrid></Modal>}
