import { useState } from 'react';
import { Pencil, RotateCcw, Trash2, UserPlus, X } from 'lucide-react';
import { useAuth } from '../../../core/auth/AuthContext';
import { useUtility } from '../UtlContext';
import { ARCHETYPES } from '../archetypes';
import { formatDate } from '../format';
import { Field, UtlCard, UtlPage } from '../components/UtlUI';

const emptyUser={name:'',email:'',employeeId:'',role:'Data Entry',branchCode:'801',active:true};
const emptyType={code:'',name:'',archetype:'SIMPLE',defaultVatRate:0,currency:'BDT',requiresConversion:false,owningDepartment:'Administration',active:true};

export default function Admin(){
  const {state,actions}=useUtility(); const {user}=useAuth(); const [form,setForm]=useState(emptyUser); const [typeForm,setTypeForm]=useState(emptyType);
  function submit(e){e.preventDefault();actions.saveUser(form);setForm(emptyUser);}
  function saveType(e){e.preventDefault();actions.saveUtilityType(typeForm);setTypeForm(emptyType);}
  function remove(u){if(u.email===user?.email){alert('You cannot delete your own active account.');return;}if(confirm(`Delete ${u.name}'s Utility assignment?`))actions.deleteUser(u.id);}
  return <UtlPage title="Utility Administration" subtitle="Manage the extensible utility catalog and the minimal Admin/Data Entry/Viewer roles." actions={<button className="utl-secondary" onClick={()=>{if(confirm('Reset Utility demo data?'))actions.reset()}}><RotateCcw size={15}/> Reset Demo</button>}>
    <UtlCard title="Utility Catalog" action={typeForm.id&&<button className="utl-secondary" onClick={()=>setTypeForm(emptyType)}><X size={14}/> Cancel Edit</button>}><form className="utl-form-grid" onSubmit={saveType}><Field label="Utility Code"><input required disabled={Boolean(typeForm.id)} value={typeForm.code} onChange={e=>setTypeForm({...typeForm,code:e.target.value})} placeholder="e.g. WASTE_COLLECTION"/></Field><Field label="Utility Name"><input required value={typeForm.name} onChange={e=>setTypeForm({...typeForm,name:e.target.value})}/></Field><Field label="Archetype"><select value={typeForm.archetype} onChange={e=>setTypeForm({...typeForm,archetype:e.target.value})}>{Object.entries(ARCHETYPES).map(([key,a])=><option key={key} value={key}>{key} — {a.label}</option>)}</select></Field><Field label="Default VAT %"><input type="number" min="0" step="0.01" value={typeForm.defaultVatRate} onChange={e=>setTypeForm({...typeForm,defaultVatRate:e.target.value})}/></Field><Field label="Currency"><select value={typeForm.currency} onChange={e=>setTypeForm({...typeForm,currency:e.target.value,requiresConversion:e.target.value!=='BDT'})}><option>BDT</option><option>USD</option><option>EUR</option><option>GBP</option></select></Field><Field label="Owning Department"><input required value={typeForm.owningDepartment} onChange={e=>setTypeForm({...typeForm,owningDepartment:e.target.value})}/></Field><button className="utl-primary" type="submit">{typeForm.id?'Update Utility':'Add Utility Type'}</button></form><div className="utl-type-list">{state.utilityTypes.map(t=><div key={t.id}><div><strong>{t.name}</strong><small>{t.code} • {t.archetype} • VAT {t.defaultVatRate}% • {t.currency}</small></div><div className="utl-row-actions"><button className="utl-icon-edit" onClick={()=>setTypeForm({...t})}><Pencil size={14}/></button><button className="utl-icon-danger" onClick={()=>{if(confirm(`Deactivate ${t.name}?`))actions.deleteUtilityType(t.id)}}><Trash2 size={14}/></button></div></div>)}</div></UtlCard>
    <div className="utl-two-col"><UtlCard title={form.id?'Edit User / Role':'Add User / Role'}><form className="utl-form-grid" onSubmit={submit}><Field label="Full Name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Email"><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Employee ID"><input required disabled={Boolean(form.id)} value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}/></Field><Field label="Role"><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>Admin</option><option>Data Entry</option><option>Viewer</option></select></Field><Field label="Branch"><select value={form.branchCode} onChange={e=>setForm({...form,branchCode:e.target.value})}>{state.branches.map(b=><option key={b.code} value={b.code}>{b.name}</option>)}</select></Field><button className="utl-primary"><UserPlus size={15}/> Save User</button></form></UtlCard><UtlCard title="System Info"><dl className="utl-def"><div><dt>Branches / Departments</dt><dd>{state.branches.length}</dd></div><div><dt>Utility types</dt><dd>{state.utilityTypes.length}</dd></div><div><dt>Bills</dt><dd>{state.bills?.filter(b=>!b.deletedAt).length||0}</dd></div></dl></UtlCard></div>
    <UtlCard title="User Management"><div className="utl-table-wrap"><table className="utl-table"><thead><tr><th>Name</th><th>Email</th><th>Employee ID</th><th>Role</th><th>Branch</th><th>Actions</th></tr></thead><tbody>{state.users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.employeeId}</td><td>{u.role}</td><td>{u.branchName}</td><td><div className="utl-row-actions"><button className="utl-icon-edit" onClick={()=>setForm({...u})}><Pencil size={14}/></button><button className="utl-icon-danger" onClick={()=>remove(u)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div></UtlCard>
    <UtlCard title="Audit Log"><div className="utl-table-wrap"><table className="utl-table"><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Detail</th></tr></thead><tbody>{state.audit.slice(0,100).map(a=><tr key={a.id}><td>{formatDate(a.timestamp)}</td><td>{a.user}</td><td><code>{a.action}</code></td><td>{a.detail}</td></tr>)}</tbody></table></div></UtlCard>
  </UtlPage>;
}
