import { useMemo, useState } from 'react';
import { Download, FileText, TrendingUp, WalletCards } from 'lucide-react';
import { useUtility } from '../UtlContext';
import { Field, UtlCard, UtlPage, UtlStat } from '../components/UtlUI';

const money=v=>new Intl.NumberFormat('en-BD',{style:'currency',currency:'BDT',maximumFractionDigits:2}).format(Number(v)||0);
const csv=v=>/[",\n]/.test(String(v??''))?`"${String(v??'').replace(/"/g,'""')}"`:String(v??'');
export default function Reports(){
  const {state}=useUtility();const [month,setMonth]=useState(new Date().toISOString().slice(0,7));const [branch,setBranch]=useState('ALL');const [utility,setUtility]=useState('ALL');
  const rows=useMemo(()=>(state.bills||[]).filter(b=>!b.deletedAt&&b.periodStart.slice(0,7)===month&&(branch==='ALL'||b.branchCode===branch)&&(utility==='ALL'||b.utilityTypeId===utility)).map(b=>({...b,typeName:state.utilityTypes.find(t=>t.id===b.utilityTypeId)?.name||b.utilityTypeId})),[state.bills,state.utilityTypes,month,branch,utility]);
  const total=rows.reduce((s,b)=>s+b.grandTotalBdt,0),delta=rows.reduce((s,b)=>s+b.deltaAmount,0),recovery=rows.flatMap(b=>b.archetype==='ASSET'?b.lines:[]).reduce((s,l)=>s+Number(l.userExpense||0),0);const variances=[...rows].sort((a,b)=>Math.abs(b.deltaAmount)-Math.abs(a.deltaAmount));
  function exportCsv(){const data=[['Period','Branch','Utility','Currency','Subtotal','VAT','Other Charges','Grand Total','Total BDT','Previous BDT','Delta BDT'],...rows.map(b=>[`${b.periodStart} to ${b.periodEnd}`,b.branchName,b.typeName,b.currency,b.subtotal,b.vatAmount,b.otherCharges,b.grandTotal,b.grandTotalBdt,b.previousAmount,b.deltaAmount])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+data.map(r=>r.map(csv).join(',')).join('\r\n')],{type:'text/csv'}));a.download=`utility-consolidated-${month}.csv`;a.click();URL.revokeObjectURL(a.href);}
  return <UtlPage title="Management Reports" subtitle="Consolidated branch and utility reporting with automatically calculated variance and staff recovery." actions={<><button className="utl-secondary" onClick={exportCsv}><Download size={15}/> Export Excel</button><button className="utl-primary" onClick={()=>window.print()}><FileText size={15}/> Export PDF</button></>}>
    <UtlCard title="Report Filters"><div className="utl-report-filters"><Field label="Month"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></Field><Field label="Branch / Department"><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="ALL">All branches</option>{state.branches.map(b=><option key={b.code} value={b.code}>{b.name}</option>)}</select></Field><Field label="Utility"><select value={utility} onChange={e=>setUtility(e.target.value)}><option value="ALL">All utilities</option>{state.utilityTypes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field></div></UtlCard>
    <div className="utl-stat-grid utl-stat-grid-three"><UtlStat label="Single Payable Total" value={money(total)} icon={<WalletCards size={18}/>}/><UtlStat label="Net Month Variance" value={`${delta>=0?'+':''}${money(delta)}`} tone={delta>0?'orange':'green'} icon={<TrendingUp size={18}/>}/><UtlStat label="Recoverable From Staff" value={money(recovery)} tone="purple"/></div>
    <UtlCard title="Monthly Consolidated — All Utilities × All Branches"><div className="utl-table-wrap"><table className="utl-table"><thead><tr><th>Branch</th><th>Utility</th><th>Period</th><th>Currency</th><th>Subtotal</th><th>VAT</th><th>Payable BDT</th><th>Delta BDT</th></tr></thead><tbody>{rows.map(b=><tr key={b.id}><td>{b.branchName}</td><td>{b.typeName}</td><td>{b.periodStart} — {b.periodEnd}</td><td>{b.currency}</td><td>{b.subtotal.toFixed(2)}</td><td>{b.vatAmount.toFixed(2)}</td><td>{money(b.grandTotalBdt)}</td><td className={b.deltaAmount>0?'utl-delta-up':'utl-delta-down'}>{b.deltaAmount>0?'+':''}{money(b.deltaAmount)}</td></tr>)}{!rows.length&&<tr><td colSpan="8">No bills match these filters.</td></tr>}</tbody></table></div></UtlCard>
    <UtlCard title="Variance Flags — Largest Changes"><div className="utl-variance-list">{variances.slice(0,10).map((b,i)=><div key={b.id}><span className={Math.abs(b.deltaAmount)>(b.previousAmount*.2)?'flag':'normal'}>{i+1}</span><div><strong>{b.typeName} — {b.branchName}</strong><small>Previous {money(b.previousAmount)} → Current {money(b.grandTotalBdt)}</small></div><b className={b.deltaAmount>0?'utl-delta-up':'utl-delta-down'}>{b.deltaAmount>0?'▲':'▼'} {money(Math.abs(b.deltaAmount))}</b></div>)}</div></UtlCard>
  </UtlPage>;
}
