import { useEffect, useMemo, useState } from 'react';
import { Download, FileSpreadsheet, Plus, Save, Trash2, Upload } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useUtility } from '../UtlContext';
import { ARCHETYPES, lineAmount } from '../archetypes';
import { parseCsv, parseXlsx } from '../spreadsheet';
import { Field, UtlCard, UtlPage, UtlStat } from '../components/UtlUI';
import UtilityDashboard from '../components/UtilityDashboard';

const csvCell=v=>/[",\n]/.test(String(v??''))?`"${String(v??'').replace(/"/g,'""')}"`:String(v??'');
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>today().slice(0,8)+'01';
const monthEnd=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth()+1,0).toISOString().slice(0,10);};
const money=(value,currency='BDT')=>new Intl.NumberFormat('en-BD',{style:'currency',currency,maximumFractionDigits:2}).format(Number(value)||0);

function FuelSetup({assets,stations,actions,onLoad}){const [asset,setAsset]=useState({name:'',vehicleNo:'',usageLimit:'No Limit'}),[station,setStation]=useState('');return <UtlCard title="Fuel Users, Vehicles & Stations"><div className="utl-fuel-master-grid"><form onSubmit={e=>{e.preventDefault();actions.saveFuelAsset(asset);setAsset({name:'',vehicleNo:'',usageLimit:'No Limit'});}}><strong>Add User / Vehicle / Generator</strong><Field label="User / Asset"><input required value={asset.name} onChange={e=>setAsset({...asset,name:e.target.value})}/></Field><Field label="Vehicle No."><input required value={asset.vehicleNo} onChange={e=>setAsset({...asset,vehicleNo:e.target.value})}/></Field><Field label="Monthly Usage Limit"><input required value={asset.usageLimit} onChange={e=>setAsset({...asset,usageLimit:e.target.value})} placeholder="No Limit or 300 L"/></Field><button className="utl-primary"><Plus size={14}/> Add User / Car</button></form><form onSubmit={e=>{e.preventDefault();actions.saveFuelStation(station);setStation('');}}><strong>Add Fuel Station</strong><Field label="Station Name"><input required value={station} onChange={e=>setStation(e.target.value)} placeholder="Another filling station"/></Field><button className="utl-primary"><Plus size={14}/> Add Station</button></form><div><strong>Configured Masters</strong><p>{assets.length} users, vehicles and generators</p><p>{stations.map(s=>s.name).join(' • ')}</p><button className="utl-secondary" onClick={onLoad}>Load all {assets.length} into monthly entry</button></div></div></UtlCard>}

export default function UtilityRegister(){
  const {typeId:routeTypeId}=useParams();const navigate=useNavigate();const {state,actions,isAdmin,ownCode,branchFilter}=useUtility();
  const types=useMemo(()=>(state.utilityTypes||[]).filter(t=>t.active||isAdmin),[state.utilityTypes,isAdmin]);
  const [typeId,setTypeId]=useState(routeTypeId||types[0]?.id||'');const type=types.find(t=>t.id===typeId)||types[0];const shape=useMemo(()=>type?.code==='FUEL'?{label:'Monthly fuel',fields:[['label','User / Asset','select'],['assetNo','Vehicle No.','readonly'],['usageLimit','Monthly Usage Limit','readonly'],['consumption','Fuel Consumption (L)','number'],['fuelStation','Fuel Station','select'],['stationAmount','Station Expense','number'],['userExpense','User Expense','number']]}:(ARCHETYPES[type?.archetype]||ARCHETYPES.SIMPLE),[type]);
  const blankLine=()=>Object.fromEntries(shape.fields.map(([key])=>[key,'']));
  const [form,setForm]=useState({branchCode:branchFilter==='ALL'?ownCode:branchFilter,periodType:'MONTH',periodStart:monthStart(),periodEnd:monthEnd(),currency:type?.currency||'BDT',conversionRate:1,vatRate:type?.defaultVatRate||0,otherCharges:0,referenceNo:'',remarks:'',attachment:null});
  const [lines,setLines]=useState([blankLine()]);const [preview,setPreview]=useState(null);const [message,setMessage]=useState('');
  useEffect(()=>{if(routeTypeId&&types.some(t=>t.id===routeTypeId))setTypeId(routeTypeId);},[routeTypeId,types]);
  useEffect(()=>{if(!type)return;setForm(f=>({...f,branchCode:type.code==='FUEL'?'801':f.branchCode,currency:type.currency,conversionRate:type.currency==='BDT'?1:f.conversionRate,vatRate:type.defaultVatRate}));setLines([Object.fromEntries(shape.fields.map(([key])=>[key,'']))]);setPreview(null);},[type,shape]);
  const calculated=useMemo(()=>{const subtotal=lines.reduce((s,l)=>s+lineAmount(type?.archetype,l),0),vat=subtotal*Number(form.vatRate||0)/100,total=subtotal+vat+Number(form.otherCharges||0);return{subtotal,vat,total,bdt:total*Number(form.currency==='BDT'?1:form.conversionRate||0)};},[lines,type?.archetype,form.vatRate,form.otherCharges,form.currency,form.conversionRate]);
  const bills=useMemo(()=>(state.bills||[]).filter(b=>!b.deletedAt&&b.utilityTypeId===type?.id&&(type?.code==='FUEL'||branchFilter==='ALL'||b.branchCode===branchFilter)),[state.bills,type?.id,type?.code,branchFilter]);
  function chooseType(id){setTypeId(id);navigate(`/utility/register/${id}`);}
  function updateLine(index,key,value){setLines(rows=>rows.map((r,i)=>{if(i!==index)return r;if(type.code==='FUEL'&&key==='label'){const asset=(state.fuelAssets||[]).find(a=>a.name===value);return{...r,label:value,assetNo:asset?.vehicleNo||'',usageLimit:asset?.usageLimit||''};}return{...r,[key]:value};}));}
  function loadFuelAssets(){setLines((state.fuelAssets||[]).filter(a=>a.active).map(a=>({...blankLine(),label:a.name,assetNo:a.vehicleNo,usageLimit:a.usageLimit})));}
  function fuelComparison(line){const prior=bills.filter(b=>b.branchCode===form.branchCode&&b.periodStart<form.periodStart).sort((a,b)=>b.periodStart.localeCompare(a.periodStart))[0],old=prior?.lines?.find(l=>(l.assetNo&&l.assetNo===line.assetNo)||l.label===line.label),previous=Number(old?.amount||0),current=lineAmount(type.archetype,line),delta=current-previous;return{previous,delta,percentage:previous?delta/previous*100:0};}
  function template(){const headers=shape.fields.map(([,label])=>label);const example=shape.fields.map(([key,,kind])=>kind==='number'?'100':key==='label'?'Sample item':`Sample ${key}`);const content=[headers,example].map(r=>r.map(csvCell).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+content],{type:'text/csv'}));a.download=`${type.code.toLowerCase()}-${type.archetype.toLowerCase()}-template.csv`;a.click();URL.revokeObjectURL(a.href);}
  async function readSheet(file){if(!file)return;setMessage('');try{const matrix=/\.xlsx$/i.test(file.name)?await parseXlsx(file):parseCsv(await file.text());const expected=shape.fields.map(([,label])=>label.toLowerCase());const actual=(matrix[0]||[]).map(x=>String(x).replace(/^\ufeff/,'').trim().toLowerCase());if(expected.some((h,i)=>actual[i]!==h))throw new Error(`Use the fixed ${type.archetype} template. Expected: ${shape.fields.map(([,l])=>l).join(', ')}`);const imported=matrix.slice(1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(shape.fields.map(([key],i)=>[key,r[i]??''])));if(!imported.length)throw new Error('The spreadsheet contains no bill lines.');setPreview({name:file.name,lines:imported});}catch(error){setPreview(null);setMessage(error.message);}}
  function acceptPreview(){setLines(preview.lines);setForm(f=>({...f,source:'IMPORT',attachment:{name:preview.name,size:0}}));setMessage(`${preview.lines.length} line(s) loaded for review. Save the bill when the totals are correct.`);setPreview(null);}
  function save(e){e.preventDefault();if(!lines.some(l=>lineAmount(type.archetype,l)>0)){setMessage('Enter at least one bill line with an amount.');return;}actions.saveBill({...form,utilityTypeId:type.id,lines,source:form.source||'MANUAL',attachment:form.attachment?{name:form.attachment.name,size:form.attachment.size,type:form.attachment.type}:null});setLines([blankLine()]);setMessage('Bill saved. VAT, totals, BDT value and period delta were calculated automatically.');}
  if(!type)return <UtlPage title="Utility Register" subtitle="No active utility type is configured."/>;
  return <UtlPage title={type.name} subtitle={`${type.archetype} archetype • ${type.owningDepartment} • one branch and one billing period per bill.`}>
    <UtilityDashboard type={type} bills={bills} branches={state.branches}/>
    {type.code==='FUEL'&&<FuelSetup assets={state.fuelAssets||[]} stations={state.fuelStations||[]} actions={actions} onLoad={loadFuelAssets}/>} 
    <div className="utl-stat-grid utl-stat-grid-three"><UtlStat label="Calculated Subtotal" value={money(calculated.subtotal,form.currency)}/><UtlStat label={`VAT ${form.vatRate||0}%`} value={money(calculated.vat,form.currency)} tone="orange"/><UtlStat label="Payable in BDT" value={money(calculated.bdt,'BDT')} tone="green"/></div>
    <UtlCard title="Bill Header"><form onSubmit={save}><div className="utl-form-grid"><Field label="Utility Type"><select value={type.id} onChange={e=>chooseType(e.target.value)}>{types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field>{type.code==='FUEL'?<Field label="Fleet Scope"><input value="Bank-wide fleet (no branch allocation)" readOnly/></Field>:<Field label="Branch / Department"><select value={form.branchCode} disabled={!isAdmin} onChange={e=>setForm({...form,branchCode:e.target.value})}>{state.branches.map(b=><option key={b.code} value={b.code}>{b.code} — {b.name}</option>)}</select></Field>}<Field label="Period Type"><select value={form.periodType} onChange={e=>setForm({...form,periodType:e.target.value})}><option value="MONTH">Month</option><option value="QUARTER">Quarter</option></select></Field><Field label="Period Start"><input type="date" required value={form.periodStart} onChange={e=>setForm({...form,periodStart:e.target.value})}/></Field><Field label="Period End"><input type="date" required min={form.periodStart} value={form.periodEnd} onChange={e=>setForm({...form,periodEnd:e.target.value})}/></Field><Field label="Invoice / Reference"><input value={form.referenceNo} onChange={e=>setForm({...form,referenceNo:e.target.value})}/></Field><Field label="Currency"><select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value,conversionRate:e.target.value==='BDT'?1:form.conversionRate})}><option>BDT</option><option>USD</option><option>EUR</option><option>GBP</option></select></Field>{form.currency!=='BDT'&&<Field label="Conversion Rate to BDT"><input type="number" required min="0.0001" step="0.0001" value={form.conversionRate} onChange={e=>setForm({...form,conversionRate:e.target.value})}/></Field>}<Field label="VAT Rate %"><input type="number" min="0" step="0.01" value={form.vatRate} onChange={e=>setForm({...form,vatRate:e.target.value})}/></Field><Field label="Other Charges"><input type="number" min="0" step="0.01" value={form.otherCharges} onChange={e=>setForm({...form,otherCharges:e.target.value})}/></Field><Field label="Source Scan / Invoice"><input type="file" accept="image/*,.pdf" onChange={e=>setForm({...form,attachment:e.target.files[0]||null})}/></Field><Field label="Remarks"><input value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></Field></div>
      <div className="utl-entry-toolbar"><strong>{shape.label} line items</strong><div><button type="button" className="utl-secondary" onClick={template}><Download size={14}/> Fixed {type.archetype} template</button><label className="utl-secondary"><Upload size={14}/> Import Excel / CSV<input hidden type="file" accept=".xlsx,.csv" onChange={e=>readSheet(e.target.files[0])}/></label><button type="button" className="utl-secondary" onClick={()=>setLines([...lines,blankLine()])}><Plus size={14}/> Add Line</button></div></div>
      <div className="utl-table-wrap"><table className="utl-table utl-entry-table"><thead><tr><th>S/L</th>{shape.fields.map(([key,label])=><th key={key}>{label}</th>)}{type.code==='FUEL'&&<><th>Previous Month</th><th>Increase / Decrease</th><th>Change %</th></>}<th>Total</th><th/></tr></thead><tbody>{lines.map((line,i)=>{const comparison=fuelComparison(line);return <tr key={i}><td>{i+1}</td>{shape.fields.map(([key,,kind])=><td key={key}>{type.code==='FUEL'&&key==='label'?<select required value={line[key]} onChange={e=>updateLine(i,key,e.target.value)}><option value="">Select user / asset</option>{(state.fuelAssets||[]).filter(a=>a.active).map(a=><option key={a.id} value={a.name}>{a.name}</option>)}</select>:type.code==='FUEL'&&key==='fuelStation'?<select required value={line[key]} onChange={e=>updateLine(i,key,e.target.value)}><option value="">Select fuel station</option>{(state.fuelStations||[]).map(s=><option key={s.id} value={s.name}>{s.name}</option>)}</select>:<input type={kind==='readonly'?'text':kind} readOnly={kind==='readonly'} step={kind==='number'?'0.01':undefined} value={line[key]} onChange={e=>updateLine(i,key,e.target.value)}/>}</td>)}{type.code==='FUEL'&&<><td>{money(comparison.previous)}</td><td className={comparison.delta>0?'utl-delta-up':'utl-delta-down'}>{comparison.delta>0?'+':''}{money(comparison.delta)}</td><td className={comparison.percentage>0?'utl-delta-up':'utl-delta-down'}>{comparison.percentage>0?'+':''}{comparison.percentage.toFixed(1)}%</td></>}<td><strong>{money(lineAmount(type.archetype,line),form.currency)}</strong></td><td><button type="button" className="utl-icon-danger" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,n)=>n!==i))}><Trash2 size={14}/></button></td></tr>})}</tbody></table></div>
      {preview&&<div className="utl-review"><FileSpreadsheet size={20}/><div><strong>{preview.name}</strong><span>{preview.lines.length} line(s) parsed with the fixed {type.archetype} template.</span></div><button type="button" className="utl-primary" onClick={acceptPreview}>Use Imported Lines</button></div>}{message&&<p className={`utl-import-message ${message.includes('saved')||message.includes('loaded')?'success':''}`}>{message}</p>}<button className="utl-primary utl-save-bill"><Save size={15}/> Save Bill</button>
    </form></UtlCard>
    <UtlCard title={`${type.name} Bill History`}><div className="utl-table-wrap"><table className="utl-table"><thead><tr><th>Period</th>{type.code!=='FUEL'&&<th>Branch</th>}<th>Source</th><th>Subtotal</th><th>VAT</th><th>Total</th><th>Total BDT</th><th>Previous</th><th>Delta</th><th>Evidence</th>{isAdmin&&<th/>}</tr></thead><tbody>{bills.map(b=><tr key={b.id}><td>{b.periodStart} — {b.periodEnd}</td>{type.code!=='FUEL'&&<td>{b.branchName}</td>}<td>{b.source}</td><td>{money(b.subtotal,b.currency)}</td><td>{money(b.vatAmount,b.currency)}</td><td>{money(b.grandTotal,b.currency)}</td><td>{money(b.grandTotalBdt)}</td><td>{money(b.previousAmount)}</td><td className={b.deltaAmount>0?'utl-delta-up':'utl-delta-down'}>{b.deltaAmount>0?'+':''}{money(b.deltaAmount)}</td><td>{b.attachment?.name||'—'}</td>{isAdmin&&<td><button className="utl-icon-danger" onClick={()=>{if(confirm('Soft-delete this bill?'))actions.deleteBill(b.id)}}><Trash2 size={14}/></button></td>}</tr>)}{!bills.length&&<tr><td colSpan={type.code==='FUEL'?10:11}>No bills saved for this utility.</td></tr>}</tbody></table></div></UtlCard>
  </UtlPage>;
}
