import { recordAudit } from '../../core/audit/store';
const KEY='cbc.inventory.module.v5';
const clone=v=>JSON.parse(JSON.stringify(v));
const now=()=>new Date().toISOString();
const today=()=>new Date().toISOString().slice(0,10);
function nextMonth(){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()+1);return d.toISOString().slice(0,7)}
function seed(){
 const branches=[{id:'801',name:'Head Office — Gulshan',type:'HQ',hubId:''},{id:'802',name:'Gulshan Branch',type:'Branch',hubId:'801'},{id:'803',name:'Agrabad Branch',type:'Hub',hubId:'801'},{id:'808',name:'Narayanganj Branch',type:'Hub',hubId:'801'}];
 const categories=[{id:1,name:'Paper & Printing',prefix:'PAP',description:'Paper, toner and print supplies'},{id:2,name:'Writing Materials',prefix:'WRT',description:'Pens, pencils and markers'},{id:3,name:'Office Essentials',prefix:'OFF',description:'Files, staplers and desk supplies'}];
 const products=[
  {id:'PAP001',name:'A4 Paper 80 GSM',category:'Paper & Printing',unit:'Ream',minStock:40,status:'Active'},
  {id:'PAP002',name:'HP 85A Toner Cartridge',category:'Paper & Printing',unit:'Piece',minStock:8,status:'Active'},
  {id:'WRT001',name:'Ball Pen — Blue',category:'Writing Materials',unit:'Box',minStock:20,status:'Active'},
  {id:'OFF001',name:'Box File',category:'Office Essentials',unit:'Piece',minStock:30,status:'Active'},
  {id:'OFF002',name:'Stapler Machine',category:'Office Essentials',unit:'Piece',minStock:10,status:'Active'},
 ];
 const stockIn=[
  {id:'SI-0001',date:today(),itemId:'PAP001',itemName:'A4 Paper 80 GSM',qty:220,remaining:160,unitCost:520,total:114400,supplier:'Bengal Stationery',invoice:'INV-2601',batchId:'BAT-001',receivedBy:'Tanzila Rahman',sourceBranch:'801',timestamp:now()},
  {id:'SI-0002',date:today(),itemId:'PAP002',itemName:'HP 85A Toner Cartridge',qty:28,remaining:20,unitCost:4900,total:137200,supplier:'Tech Supplies Ltd.',invoice:'INV-2602',batchId:'BAT-002',receivedBy:'Tanzila Rahman',sourceBranch:'801',timestamp:now()},
  {id:'SI-0003',date:today(),itemId:'WRT001',itemName:'Ball Pen — Blue',qty:100,remaining:82,unitCost:420,total:42000,supplier:'Bengal Stationery',invoice:'INV-2603',batchId:'BAT-003',receivedBy:'Tanzila Rahman',sourceBranch:'801',timestamp:now()},
  {id:'SI-0004',date:today(),itemId:'OFF001',itemName:'Box File',qty:140,remaining:105,unitCost:155,total:21700,supplier:'Office Mart',invoice:'INV-2604',batchId:'BAT-004',receivedBy:'Tanzila Rahman',sourceBranch:'801',timestamp:now()},
 ];
 const requests=[
  {id:1,no:'REQ-2026-0001',month:nextMonth(),date:today(),routeType:'BRANCH',branchId:'802',branchName:'Gulshan Branch',deptId:3,deptName:'Operations',requesterEmployeeId:'BNGL0610',requesterName:'Rakib Hasan',purpose:'Monthly stationery requirement',requesterNote:'Required by first working week.',status:'PENDING',managerNote:'',procurementNote:'',receiptStatus:'NOT_DISPATCHED',createdAt:now(),updatedAt:now(),items:[{lineId:1,itemId:'PAP001',itemName:'A4 Paper 80 GSM',unit:'Ream',requestedQty:20,approvedQty:0,suppliedQty:0,receivedQty:0,managerNote:'',procurementNote:''},{lineId:2,itemId:'WRT001',itemName:'Ball Pen — Blue',unit:'Box',requestedQty:8,approvedQty:0,suppliedQty:0,receivedQty:0,managerNote:'',procurementNote:''}],timeline:[{id:1,event:'SUBMITTED',by:'Rakib Hasan',at:now(),note:'Submitted for branch manager approval.'}]},
  {id:2,no:'REQ-2026-0002',month:nextMonth(),date:today(),routeType:'DEPT',branchId:'801',branchName:'Head Office — Gulshan',deptId:1,deptName:'Information Technology',requesterEmployeeId:'BNGL0611',requesterName:'Farhana Islam',purpose:'Printer and filing supplies',requesterNote:'',status:'PENDING_ADMIN',managerNote:'Approved for next month.',procurementNote:'',receiptStatus:'NOT_DISPATCHED',createdAt:now(),updatedAt:now(),items:[{lineId:3,itemId:'PAP002',itemName:'HP 85A Toner Cartridge',unit:'Piece',requestedQty:4,approvedQty:3,suppliedQty:0,receivedQty:0,managerNote:'Approved 3 units.',procurementNote:''},{lineId:4,itemId:'OFF001',itemName:'Box File',unit:'Piece',requestedQty:25,approvedQty:20,suppliedQty:0,receivedQty:0,managerNote:'',procurementNote:''}],timeline:[{id:2,event:'SUBMITTED',by:'Farhana Islam',at:now(),note:''},{id:3,event:'APPROVED',by:'Kamrul Ahsan',at:now(),note:'Approved for next month.'}]},
 ];
 const receipts=[{id:'RV-0001',date:today(),requestNo:'REQ-2026-0000',batchId:'BAT-001',itemId:'PAP001',itemName:'A4 Paper 80 GSM',branchId:'802',branchName:'Gulshan Branch',qtyExpected:40,qtyReceived:40,difference:0,unitCost:520,total:20800,receivedBy:'Rakib Hasan',note:'Received in good condition',timestamp:now()}];
 const consumption=[{id:'CON-0001',date:today(),itemId:'PAP001',itemName:'A4 Paper 80 GSM',branchId:'802',branchName:'Gulshan Branch',qty:8,avgCost:520,total:4160,purpose:'Daily printing',recordedBy:'Rakib Hasan',timestamp:now()}];
 const transactions=[{id:'TXN-0001',date:today(),type:'STOCK_IN',ref:'SI-0001',itemId:'PAP001',itemName:'A4 Paper 80 GSM',unit:'Ream',qty:220,unitCost:520,total:114400,sourceBranch:'Supplier',destBranch:'801',by:'Tanzila Rahman',timestamp:now()},{id:'TXN-0002',date:today(),type:'BRANCH_RECEIPT',ref:'RV-0001',itemId:'PAP001',itemName:'A4 Paper 80 GSM',unit:'Ream',qty:40,unitCost:520,total:20800,sourceBranch:'801',destBranch:'802',by:'Rakib Hasan',timestamp:now()},{id:'TXN-0003',date:today(),type:'CONSUMPTION',ref:'CON-0001',itemId:'PAP001',itemName:'A4 Paper 80 GSM',unit:'Ream',qty:8,unitCost:520,total:4160,sourceBranch:'802',destBranch:'Used',by:'Rakib Hasan',timestamp:now()}];
 return {branches,categories,products,stockIn,requests,receipts,consumption,transactions,audit:[{id:1,timestamp:now(),event:'MODULE_INITIALISED',user:'system',detail:'Inventory demo data created.',status:'OK'}],seq:{request:3,line:5,stock:5,receipt:2,consumption:2,transaction:4,audit:2,category:4}};
}
export function loadState(){try{const raw=localStorage.getItem(KEY);if(raw)return JSON.parse(raw)}catch{}const s=seed();saveState(s);return s}
export function saveState(s){localStorage.setItem(KEY,JSON.stringify(s));return s}
function mutate(fn){const s=loadState();fn(s);return saveState(s)}
function actorName(a){return a?.displayName||a?.email||'User'}
function audit(s,event,actor,detail,status='OK'){s.audit.unshift({id:s.seq.audit++,timestamp:now(),event,user:actor?.email||actorName(actor),detail,status});recordAudit({moduleCode:'inv',action:event,detail,actor,status:status==='OK'?'SUCCESS':'FAILED'})}
function txn(s,p){s.transactions.unshift({id:`TXN-${String(s.seq.transaction++).padStart(4,'0')}`,date:today(),timestamp:now(),...p})}
export function reset(actor){const s=seed();saveState(s);recordAudit({moduleCode:'inv',action:'DEMO_RESET',detail:'Stationery Inventory demonstration data reset.',actor});return clone(s)}
export function centerStock(state){return state.products.map(p=>{const batches=state.stockIn.filter(b=>b.itemId===p.id);const qty=batches.reduce((a,b)=>a+Number(b.remaining||0),0);const value=batches.reduce((a,b)=>a+Number(b.remaining||0)*Number(b.unitCost||0),0);return {...p,stock:qty,avgCost:qty?value/qty:0,totalValue:value,batches:batches.filter(b=>b.remaining>0).length}})}
export function branchStock(state,branchId){const branches=branchId?[state.branches.find(b=>b.id===branchId)].filter(Boolean):state.branches.filter(b=>b.id!=='801');const rows=[];for(const b of branches){for(const p of state.products){const received=state.receipts.filter(r=>r.branchId===b.id&&r.itemId===p.id).reduce((a,r)=>a+Number(r.qtyReceived||0),0);const used=state.consumption.filter(r=>r.branchId===b.id&&r.itemId===p.id).reduce((a,r)=>a+Number(r.qty||0),0);const stock=received-used;if(stock||received)rows.push({branchId:b.id,branchName:b.name,itemId:p.id,itemName:p.name,unit:p.unit,stock,avgCost:averageReceiptCost(state,b.id,p.id),minStock:p.minStock,totalValue:stock*averageReceiptCost(state,b.id,p.id)})}}return rows}
function averageReceiptCost(s,bid,iid){const rr=s.receipts.filter(r=>r.branchId===bid&&r.itemId===iid);const qty=rr.reduce((a,r)=>a+Number(r.qtyReceived||0),0);return qty?rr.reduce((a,r)=>a+Number(r.total||0),0)/qty:0}
function appendTimeline(r,event,actor,note=''){r.timeline.push({id:Date.now()+Math.random(),event,by:actorName(actor),at:now(),note})}
export function saveProduct(payload,actor){return mutate(s=>{const old=s.products.find(p=>p.id===payload.id);if(old)Object.assign(old,payload);else s.products.push({...payload,status:payload.status||'Active'});audit(s,old?'PRODUCT_UPDATE':'PRODUCT_ADD',actor,`${payload.id} ${payload.name}`)})}
export function saveCategory(payload,actor){return mutate(s=>{if(payload.id){const x=s.categories.find(c=>c.id===payload.id);Object.assign(x,payload)}else s.categories.push({...payload,id:s.seq.category++});audit(s,payload.id?'CATEGORY_UPDATE':'CATEGORY_ADD',actor,payload.name)})}
export function saveBranch(payload,actor){return mutate(s=>{const old=s.branches.find(b=>b.id===payload.id);if(old)Object.assign(old,payload);else s.branches.push({...payload});audit(s,old?'BRANCH_UPDATE':'BRANCH_ADD',actor,`${payload.id} ${payload.name}`)})}
export function receiveStock(payload,actor){return mutate(s=>{const p=s.products.find(x=>x.id===payload.itemId);const qty=Number(payload.qty),cost=Number(payload.unitCost);const id=`SI-${String(s.seq.stock++).padStart(4,'0')}`,batchId=`BAT-${String(s.seq.stock).padStart(3,'0')}`;s.stockIn.unshift({id,date:payload.date||today(),itemId:p.id,itemName:p.name,qty,remaining:qty,unitCost:cost,total:qty*cost,supplier:payload.supplier,invoice:payload.invoice||'',batchId,receivedBy:actorName(actor),sourceBranch:'801',timestamp:now()});txn(s,{type:'STOCK_IN',ref:id,itemId:p.id,itemName:p.name,unit:p.unit,qty,unitCost:cost,total:qty*cost,sourceBranch:'Supplier',destBranch:'801',by:actorName(actor)});audit(s,'STOCK_IN',actor,`${p.name}: ${qty} ${p.unit}`)})}
export function createRequest(payload,actor,submit=true){let created;mutate(s=>{const id=s.seq.request++;const no=`REQ-${new Date().getFullYear()}-${String(id).padStart(4,'0')}`;created={id,no,month:payload.month,date:today(),routeType:payload.routeType,branchId:payload.branchId,branchName:payload.branchName,deptId:payload.deptId,deptName:payload.deptName,requesterEmployeeId:actor?.employeeId,requesterName:actorName(actor),purpose:payload.purpose,requesterNote:payload.requesterNote||'',status:submit?'PENDING':'DRAFT',managerNote:'',procurementNote:'',receiptStatus:'NOT_DISPATCHED',createdAt:now(),updatedAt:now(),items:payload.items.map(x=>{const p=s.products.find(p=>p.id===x.itemId);return{lineId:s.seq.line++,itemId:p.id,itemName:p.name,unit:p.unit,requestedQty:Number(x.requestedQty),approvedQty:0,suppliedQty:0,receivedQty:0,managerNote:'',procurementNote:''}}),timeline:[]};appendTimeline(created,submit?'SUBMITTED':'DRAFT_SAVED',actor,payload.requesterNote||'');s.requests.unshift(created);audit(s,submit?'REQUEST_SUBMIT':'REQUEST_DRAFT',actor,no)});return created}
export function submitRequest(id,actor){return mutate(s=>{const r=s.requests.find(x=>x.id===id);if(!['DRAFT','RETURNED'].includes(r.status))throw Error('Only draft or returned requisitions can be submitted.');r.status='PENDING';r.updatedAt=now();appendTimeline(r,'SUBMITTED',actor,'Submitted for approval.');audit(s,'REQUEST_SUBMIT',actor,r.no)})}
export function approveRequest(id,lines,note,actor){return mutate(s=>{const r=s.requests.find(x=>x.id===id);if(r.status!=='PENDING')throw Error('Request is not awaiting approval.');r.items.forEach(x=>{const l=lines.find(v=>v.lineId===x.lineId);x.approvedQty=Number(l?.approvedQty||0);x.managerNote=l?.managerNote||''});r.managerNote=note||'';r.status='PENDING_ADMIN';r.updatedAt=now();appendTimeline(r,'APPROVED',actor,note);audit(s,'REQUEST_APPROVE',actor,r.no)})}
export function returnRequest(id,note,actor){return mutate(s=>{const r=s.requests.find(x=>x.id===id);r.status='RETURNED';r.managerNote=note;r.updatedAt=now();appendTimeline(r,'RETURNED',actor,note);audit(s,'REQUEST_RETURN',actor,r.no)})}
export function rejectRequest(id,note,actor){return mutate(s=>{const r=s.requests.find(x=>x.id===id);r.status='REJECTED';r.managerNote=note;r.updatedAt=now();appendTimeline(r,'REJECTED',actor,note);audit(s,'REQUEST_REJECT',actor,r.no,'REJECTED')})}
export function cancelRequest(id,note,actor){return mutate(s=>{const r=s.requests.find(x=>x.id===id);r.status='CANCELLED';r.updatedAt=now();appendTimeline(r,'CANCELLED',actor,note);audit(s,'REQUEST_CANCEL',actor,r.no)})}
function fifo(s,itemId,qty){let remaining=qty,total=0;const used=[];for(const b of s.stockIn.filter(x=>x.itemId===itemId&&x.remaining>0).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id))){const take=Math.min(remaining,b.remaining);if(take<=0)continue;b.remaining-=take;remaining-=take;total+=take*b.unitCost;used.push({batchId:b.batchId,qty:take,unitCost:b.unitCost});if(remaining<=0)break}if(remaining>0)throw Error('Insufficient centre stock.');return{used,total,avgCost:qty?total/qty:0}}
export function dispatchRequest(id,lines,note,actor){return mutate(s=>{const r=s.requests.find(x=>x.id===id);if(!['PENDING_ADMIN','PARTIALLY_ISSUED'].includes(r.status))throw Error('Request is not available for dispatch.');for(const line of lines){const item=r.items.find(x=>x.lineId===line.lineId);const qty=Number(line.issueQty||0);if(qty<=0)continue;const balance=item.approvedQty-item.suppliedQty;if(qty>balance)throw Error(`Issue quantity exceeds approved balance for ${item.itemName}.`);const valuation=fifo(s,item.itemId,qty);item.suppliedQty+=qty;item.procurementNote=line.procurementNote||'';txn(s,{type:'DISPATCH',ref:r.no,itemId:item.itemId,itemName:item.itemName,unit:item.unit,qty,unitCost:valuation.avgCost,total:valuation.total,sourceBranch:'801',destBranch:r.branchId,by:actorName(actor),batchDetail:valuation.used});}r.procurementNote=note||'';const complete=r.items.every(x=>x.approvedQty===0||x.suppliedQty>=x.approvedQty);r.status=complete?'ISSUED':'PARTIALLY_ISSUED';r.receiptStatus='AWAITING_RECEIPT';r.updatedAt=now();appendTimeline(r,complete?'ISSUED':'PARTIALLY_ISSUED',actor,note);audit(s,'REQUEST_DISPATCH',actor,`${r.no} · ${r.status}`)})}
export function declineRequest(id,note,actor){return mutate(s=>{const r=s.requests.find(x=>x.id===id);r.status='DECLINED';r.procurementNote=note;appendTimeline(r,'DECLINED',actor,note);audit(s,'REQUEST_DECLINE',actor,r.no,'DECLINED')})}
export function confirmReceipt(id,lines,note,actor){return mutate(s=>{const r=s.requests.find(x=>x.id===id);for(const x of lines){const item=r.items.find(i=>i.lineId===x.lineId);const qty=Number(x.receivedQty||0);if(qty<0||qty>item.suppliedQty-item.receivedQty)throw Error('Invalid received quantity.');if(qty===0)continue;item.receivedQty+=qty;const tx=s.transactions.find(t=>t.type==='DISPATCH'&&t.ref===r.no&&t.itemId===item.itemId);const cost=Number(tx?.unitCost||0);const rid=`RV-${String(s.seq.receipt++).padStart(4,'0')}`;s.receipts.unshift({id:rid,date:today(),requestNo:r.no,batchId:'FIFO',itemId:item.itemId,itemName:item.itemName,branchId:r.branchId,branchName:r.branchName,qtyExpected:item.suppliedQty,qtyReceived:qty,difference:item.suppliedQty-item.receivedQty,unitCost:cost,total:qty*cost,receivedBy:actorName(actor),note:note||'',timestamp:now()});txn(s,{type:'BRANCH_RECEIPT',ref:rid,itemId:item.itemId,itemName:item.itemName,unit:item.unit,qty,unitCost:cost,total:qty*cost,sourceBranch:'801',destBranch:r.branchId,by:actorName(actor)});}r.receiptStatus=r.items.every(x=>x.receivedQty>=x.suppliedQty)?'CONFIRMED':'PARTIAL_RECEIPT';appendTimeline(r,'RECEIPT_CONFIRMED',actor,note);audit(s,'RECEIPT_CONFIRM',actor,r.no)})}
export function recordConsumption(payload,actor){return mutate(s=>{const p=s.products.find(x=>x.id===payload.itemId);const stock=branchStock(s,payload.branchId).find(x=>x.itemId===payload.itemId)?.stock||0;const qty=Number(payload.qty);if(qty>stock)throw Error('Consumption exceeds branch stock.');const cost=averageReceiptCost(s,payload.branchId,payload.itemId);const id=`CON-${String(s.seq.consumption++).padStart(4,'0')}`;const b=s.branches.find(x=>x.id===payload.branchId);s.consumption.unshift({id,date:payload.date||today(),itemId:p.id,itemName:p.name,branchId:b.id,branchName:b.name,qty,avgCost:cost,total:qty*cost,purpose:payload.purpose,recordedBy:actorName(actor),timestamp:now()});txn(s,{type:'CONSUMPTION',ref:id,itemId:p.id,itemName:p.name,unit:p.unit,qty,unitCost:cost,total:qty*cost,sourceBranch:b.id,destBranch:'Used',by:actorName(actor)});audit(s,'CONSUMPTION',actor,`${b.name}: ${p.name} ${qty}`)})}
export function visibleRequests(state,auth){if(auth.isSuperAdmin||auth.can('inv.requisition.issue'))return state.requests;if(auth.can('inv.requisition.approve')){const scope=auth.scopeOf('inv.requisition.approve');return state.requests.filter(r=>{const portalBranchId=Number(String(r.branchId).replace(/^80/,''));return scope?.scopeType==='BRANCH'?scope.branchIds.includes(portalBranchId):scope?.scopeType==='DEPT'?scope.deptIds.includes(r.deptId):false})}return state.requests.filter(r=>r.requesterEmployeeId===auth.user?.employeeId)}
