import { useCallback, useEffect, useState } from 'react';
import { Car, Edit3, Plus, Trash2, UserRound } from 'lucide-react';
import { PageHeader, Panel, FormField, FormGrid, EmptyState } from '../../../core/ui';
import Modal from '../../../core/ui/Modal';
import { useAuth } from '../../../core/auth/AuthContext';
import { createDriver, createVehicle, deleteDriver, deleteVehicle, getFleet, updateDriver, updateVehicle } from '../api';

export default function FleetScreen(){
  const {can}=useAuth(); const [data,setData]=useState(null); const [error,setError]=useState(''); const [vehicle,setVehicle]=useState(null); const [driver,setDriver]=useState(null);
  const load=useCallback(()=>getFleet().then(setData).catch((e)=>setError(e.response?.data?.error||'Could not load fleet.')),[]); useEffect(()=>{load()},[load]);
  async function removeVehicle(row){if(!window.confirm(`Delete vehicle ${row.regNo}?`))return;try{await deleteVehicle(row.vehicleId);load()}catch(e){window.alert(e.response?.data?.error||e.message)}}
  async function removeDriver(row){if(!window.confirm(`Delete driver ${row.fullName}?`))return;try{await deleteDriver(row.driverId);load()}catch(e){window.alert(e.response?.data?.error||e.message)}}
  if(error)return <div><PageHeader title="Fleet Management"/><div className="alert-error">{error}</div></div>;
  if(!data)return <div className="ui-empty">Loading fleet…</div>;
  return <div><PageHeader title="Fleet Management" subtitle="Add and maintain official vehicles and drivers used by the booking workflow.">{can('vbs.vehicle.manage')&&<button className="btn btn-primary" onClick={()=>setVehicle({})}><Plus size={15}/>Add vehicle</button>}{can('vbs.driver.manage')&&<button className="btn btn-secondary" onClick={()=>setDriver({})}><Plus size={15}/>Add driver</button>}</PageHeader>
    <div className="vbs-fleet-grid">
      <Panel title={`Vehicles (${data.vehicles.length})`} padded={false}>{!data.vehicles.length?<EmptyState icon={Car} title="No vehicles"/>:<div style={{overflow:'auto'}}><table className="ui-table"><thead><tr><th>Registration</th><th>Make / Model</th><th>Seats</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.vehicles.map((v)=><tr key={v.vehicleId}><td className="code">{v.regNo}</td><td>{v.make} {v.model}</td><td>{v.seatCapacity}</td><td><span className={`vbs-master-status ${String(v.status).toLowerCase()}`}>{v.status}</span></td><td><div className="ins-row-actions">{can('vbs.vehicle.manage')&&<><button className="vbs-act vbs-act-edit" title="Edit vehicle" onClick={()=>setVehicle(v)}><Edit3 size={14}/></button><button className="vbs-act vbs-act-no" title="Delete vehicle" onClick={()=>removeVehicle(v)}><Trash2 size={14}/></button></>}</div></td></tr>)}</tbody></table></div>}</Panel>
      <Panel title={`Drivers (${data.drivers.length})`} padded={false}>{!data.drivers.length?<EmptyState icon={UserRound} title="No drivers"/>:<div style={{overflow:'auto'}}><table className="ui-table"><thead><tr><th>Driver</th><th>Phone</th><th>Licence No.</th><th>Expiry</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.drivers.map((d)=><tr key={d.driverId}><td><strong>{d.fullName}</strong></td><td>{d.phone}</td><td className="code">{d.licenseNo||'—'}</td><td>{d.licenseExpiry}</td><td><span className={`vbs-master-status ${String(d.status||'ACTIVE').toLowerCase()}`}>{d.status||'ACTIVE'}</span></td><td>{can('vbs.driver.manage')&&<div className="ins-row-actions"><button className="vbs-act vbs-act-edit" title="Edit driver" onClick={()=>setDriver(d)}><Edit3 size={14}/></button><button className="vbs-act vbs-act-no" title="Delete driver" onClick={()=>removeDriver(d)}><Trash2 size={14}/></button></div>}</td></tr>)}</tbody></table></div>}</Panel>
    </div>
    {vehicle&&<VehicleModal row={vehicle} onClose={()=>setVehicle(null)} onSaved={()=>{setVehicle(null);load()}}/>}{driver&&<DriverModal row={driver} onClose={()=>setDriver(null)} onSaved={()=>{setDriver(null);load()}}/>}
  </div>;
}
function VehicleModal({row,onClose,onSaved}){const editing=Boolean(row.vehicleId);const [form,setForm]=useState({regNo:row.regNo||'',make:row.make||'',model:row.model||'',seatCapacity:row.seatCapacity||4,status:row.status||'AVAILABLE'});const [error,setError]=useState('');const set=(k,v)=>setForm((o)=>({...o,[k]:v}));async function save(e){e.preventDefault();setError('');try{if(editing)await updateVehicle(row.vehicleId,form);else await createVehicle(form);onSaved()}catch(err){setError(err.response?.data?.error||err.message)}}return <Modal title={`${editing?'Edit':'Add'} Vehicle`} onClose={onClose} footer={<><button className="btn btn-secondary" onClick={onClose}>Cancel</button><button form="vbs-vehicle-form" className="btn btn-primary" type="submit">Save vehicle</button></>}><form id="vbs-vehicle-form" onSubmit={save}>{error&&<div className="alert-error">{error}</div>}<FormGrid><FormField label="Registration No." required><input value={form.regNo} onChange={(e)=>set('regNo',e.target.value)}/></FormField><FormField label="Seat Capacity" required><input type="number" min="1" value={form.seatCapacity} onChange={(e)=>set('seatCapacity',e.target.value)}/></FormField><FormField label="Make" required><input value={form.make} onChange={(e)=>set('make',e.target.value)}/></FormField><FormField label="Model" required><input value={form.model} onChange={(e)=>set('model',e.target.value)}/></FormField><FormField label="Status"><select value={form.status} onChange={(e)=>set('status',e.target.value)}><option>AVAILABLE</option><option>MAINTENANCE</option><option>INACTIVE</option></select></FormField></FormGrid></form></Modal>}
function DriverModal({row,onClose,onSaved}){const editing=Boolean(row.driverId);const [form,setForm]=useState({fullName:row.fullName||'',phone:row.phone||'',licenseNo:row.licenseNo||'',licenseExpiry:row.licenseExpiry||'',status:row.status||'ACTIVE'});const [error,setError]=useState('');const set=(k,v)=>setForm((o)=>({...o,[k]:v}));async function save(e){e.preventDefault();setError('');try{if(editing)await updateDriver(row.driverId,form);else await createDriver(form);onSaved()}catch(err){setError(err.response?.data?.error||err.message)}}return <Modal title={`${editing?'Edit':'Add'} Driver`} onClose={onClose} footer={<><button className="btn btn-secondary" onClick={onClose}>Cancel</button><button form="vbs-driver-form" className="btn btn-primary" type="submit">Save driver</button></>}><form id="vbs-driver-form" onSubmit={save}>{error&&<div className="alert-error">{error}</div>}<FormGrid><FormField label="Full Name" required><input value={form.fullName} onChange={(e)=>set('fullName',e.target.value)}/></FormField><FormField label="Phone" required><input value={form.phone} onChange={(e)=>set('phone',e.target.value)}/></FormField><FormField label="Licence No."><input value={form.licenseNo} onChange={(e)=>set('licenseNo',e.target.value)}/></FormField><FormField label="Licence Expiry" required><input type="date" value={form.licenseExpiry} onChange={(e)=>set('licenseExpiry',e.target.value)}/></FormField><FormField label="Status"><select value={form.status} onChange={(e)=>set('status',e.target.value)}><option>ACTIVE</option><option>ON_LEAVE</option><option>INACTIVE</option></select></FormField></FormGrid></form></Modal>}
