import { useMemo, useState } from 'react';
import { Download, FileBarChart2 } from 'lucide-react';
import { PageHeader, Panel, StatTile } from '../../../core/ui';
import { usePaper } from '../PprContext';
import { summarize, monthlyTrend } from '../store';

export default function Reports(){
  const {entries,directory,state,exportCsv}=usePaper(); const [from,setFrom]=useState('');const [to,setTo]=useState('');const [branch,setBranch]=useState('ALL');const [dept,setDept]=useState('ALL');const [paper,setPaper]=useState('ALL');
  const rows=useMemo(()=>entries.filter((r)=>(!from||r.month>=from)&&(!to||r.month<=to)&&(branch==='ALL'||r.branchId===Number(branch))&&(dept==='ALL'||r.deptId===Number(dept))&&(paper==='ALL'||r.paperTypeId===Number(paper))),[entries,from,to,branch,dept,paper]);
  const summary=useMemo(()=>summarize(rows),[rows]);const trend=useMemo(()=>monthlyTrend(rows),[rows]);
  const byUnit=useMemo(()=>{const m=new Map();for(const r of rows){const k=`${r.branchName}|${r.deptName}`;const x=m.get(k)||{branch:r.branchName,dept:r.deptName,pages:0,entries:0,requisition:0};x.pages+=r.totalPagesUsed;x.entries++;if(r.requisitionUnit.toLowerCase().startsWith('rim'))x.requisition+=r.requisitionQty;m.set(k,x)}return[...m.values()].sort((a,b)=>b.pages-a.pages)},[rows]);
  function download(){const blob=new Blob([exportCsv(rows)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`paper-usage-report-${from||'start'}-${to||'latest'}.csv`;a.click();URL.revokeObjectURL(url)}
  return <div className="ppr-page"><PageHeader title="Paper Usage Reports" subtitle="Generate a filtered report by month, branch, department, printer scope, and paper type."><button className="btn btn-primary" onClick={download}><Download size={15}/>Export CSV</button></PageHeader><Panel><div className="ppr-report-filter"><label>From<input type="month" value={from} onChange={(e)=>setFrom(e.target.value)}/></label><label>To<input type="month" value={to} onChange={(e)=>setTo(e.target.value)}/></label><label>Branch<select value={branch} onChange={(e)=>{setBranch(e.target.value);setDept('ALL')}}><option value="ALL">All branches</option>{directory.branches.map((b)=><option key={b.branchId} value={b.branchId}>{b.name}</option>)}</select></label><label>Department<select value={dept} onChange={(e)=>setDept(e.target.value)}><option value="ALL">All departments</option>{directory.departments.filter((d)=>branch==='ALL'||d.branchId===Number(branch)).map((d)=><option key={d.deptId} value={d.deptId}>{d.name}</option>)}</select></label><label>Paper Type<select value={paper} onChange={(e)=>setPaper(e.target.value)}><option value="ALL">All paper types</option>{state.paperTypes.map((p)=><option key={p.paperTypeId} value={p.paperTypeId}>{p.name}</option>)}</select></label></div></Panel><div className="ui-stat-grid ppr-report-stats"><StatTile label="Pages Used" value={summary.pages.toLocaleString()} icon={FileBarChart2}/><StatTile label="Entries" value={rows.length.toLocaleString()} icon={FileBarChart2}/><StatTile label="Requested Rims" value={summary.requisitionRims.toLocaleString()} icon={FileBarChart2}/><StatTile label="Reporting Units" value={byUnit.length.toLocaleString()} icon={FileBarChart2}/></div><div className="ppr-dashboard-grid"><Panel title="Monthly Totals"><div className="ppr-report-bars">{trend.map((r)=><div key={r.month}><span className="code">{r.month}</span><div><i style={{width:`${summary.pages?Math.max(1,r.pages/Math.max(...trend.map(x=>x.pages))*100):0}%`}}/></div><strong>{r.pages.toLocaleString()}</strong></div>)}</div></Panel><Panel title="Branch / Department Summary" padded={false}><div className="ppr-table-wrap"><table className="ui-table"><thead><tr><th>Branch</th><th>Department / Scope</th><th>Entries</th><th>Pages</th><th>Next Requisition</th></tr></thead><tbody>{byUnit.map((r)=><tr key={`${r.branch}-${r.dept}`}><td>{r.branch}</td><td>{r.dept}</td><td>{r.entries}</td><td><strong>{r.pages.toLocaleString()}</strong></td><td>{r.requisition.toLocaleString()} rims</td></tr>)}</tbody><tfoot><tr><th colSpan="2">Total Portfolio</th><th>{rows.length}</th><th>{summary.pages.toLocaleString()}</th><th>{summary.requisitionRims.toLocaleString()} rims</th></tr></tfoot></table></div></Panel></div></div>;
}
